---
micronaut:
  application:
    name: studio-admin-test2

---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 0.1
---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
datasources.default: {}